#--------------------------------------------------------------------------------------------------
# YAML File for Trigger Monitoring Dashboard
#
# Author - Nitin Magima
# Date - 2024
# Version - 1.0
#--------------------------------------------------------------------------------------------------

#==================================================================================================
#
# IMPORTANT - DISCLAIMER AND RIGHTS STATEMENT
# This is a set of scripts written by the Financial Instruments Team at the International Research
# Institute for Climate and Society (IRI) part of The Columbia Climate School, Columbia University
# They are shared for educational purposes only.  Anyone who uses this code or its
# functionality or structure, assumes full liability and should inform and credit IRI.
#
#==================================================================================================

maprooms:
    djibouti:
      maproom: "djibouti"
      country: "djibouti" #this is different from country as sometimes the season is included in this variable
      target_season: "JAS" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
#        - name: District
#          key: 2
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2023
      issue_month: [5,4,3]
      freq: [15,30]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/djibouti"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    djibouti-mam:
      maproom: "djibouti-mam"
      country: "djibouti" #this is different from country as sometimes the season is included in this variable
      target_season: "MAM" #this is different from season below which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      #        - name: District
      #          key: 2
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2023
      issue_month: [1]
      freq: [ 15,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/djibouti-mam"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    djibouti-ond:
      maproom: "djibouti-ond"
      country: "djibouti" #this is different from country as sometimes the season is included in this variable
      target_season: "OND" #this is different from season below which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      #        - name: District
      #          key: 2
      season: "season1"
      predictor: "pnep-2023"
      predictand: "bad-years"
      year: 2023
      issue_month: [ 8 ]
      freq: [ 15,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/djibouti-ond"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    madagascar:
      maproom: "madagascar"
      country: "madagascar"
      target_season: "DJF" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      season: "season1"
      predictor: "pnep-v2"
      predictand: "bad-years-v3"
      year: 2024
      issue_month: [ 10,9,8 ]
      freq: [ 15, 25, 35 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/madagascar"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 2

    madagascar-ond:
      maproom: "madagascar-ond"
      country: "madagascar"
      target_season: "OND" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2024
      issue_month: [8,7,6]
      freq: [ 15, 25, 35 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/madagascar-ond"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 2

    ethiopia:
      maproom: "ethiopia"
      country: "ethiopia"
      target_season: "MAM" #this is different from season which is used for the API
      mode:
        - name: Regional
          key: 0
        - name: Zonal
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2024
      issue_month: [1, 0, 11]
      freq: [ 20,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/ethiopia"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    ethiopia-ond:
      maproom: "ethiopia-ond"
      country: "ethiopia"
      target_season: "OND" #this is different from season which is used for the API
      mode:
        - name: Regional
          key: 0
        - name: Zonal
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2024
      issue_month: [8,7,6]
      freq: [ 20,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/ethiopia-ond"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    southern-oromia:
      maproom: "southern-oromia"
      country: "southern oromia"
      target_season: "MAM" #this is different from season which is used for the API
      mode:
        - name: Project Region
          key: 0
        - name: Zonal
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2024
      issue_month: [1, 0, 11]
      freq: [ 20,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/southern-oromia"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    southern-oromia-ond:
      maproom: "southern-oromia-ond"
      country: "southern oromia"
      target_season: "OND" #this is different from season which is used for the API
      mode:
        - name: Project Region
          key: 0
        - name: Zonal
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2024
      issue_month: [ 8, 7, 6 ]
      freq: [ 20,30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/southern-oromia-ond"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 0

    niger:
      maproom: "niger"
      country: "niger"
      target_season: "JAS" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years-v3"
      year: 2024
      issue_month: [5, 4, 3, 2, 1, 0]
      freq: [ 15, 25, 35 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/niger"
      report: "https://google.com"
      username: None
      password: None
      threshold_protocol: 2

    lesotho:
      maproom: "lesotho"
      country: "lesotho"
      target_season: "DJF" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: District
          key: 1
      season: "season1"
      predictor: "pnep-v2"
      predictand: "bad-years-ag"
      year: 2023
      issue_month: [10, 9, 8]
      freq: [ 15, 25, 35 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/lesotho"
      report: "https://google.com"
      username: "lms"
      password: "maseru*newyork"
      threshold_protocol: 0

    lesotho-ond:
      maproom: "lesotho-ond"
      country: "lesotho"
      target_season: "OND" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: District
          key: 1
      season: "season1"
      predictor: "pnep-v2"
      predictand: "bad-years-ag"
      year: 2023
      issue_month: [8, 7, 6, 5]
      freq: [ 15, 25, 35 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/lesotho-ond"
      report: "https://google.com"
      username: "lms"
      password: "maseru*newyork"
      threshold_protocol: 0