#--------------------------------------------------------------------------------------------------
# YAML File for Trigger Monitoring Dashboard
#
# Author - Nitin Magima
# Date - 2024
# Version - 1.0
#--------------------------------------------------------------------------------------------------

#==================================================================================================
#
# IMPORTANT - DISCLAIMER AND RIGHTS STATEMENT
# This is a set of scripts written by the Financial Instruments Team at the International Research
# Institute for Climate and Society (IRI) part of The Columbia Climate School, Columbia University
# They are shared for educational purposes only.  Anyone who uses this code or its
# functionality or structure, assumes full liability and should inform and credit IRI.
#
#==================================================================================================

countries:
    djibouti:
      country: "djibouti" #this is different from country as sometimes the season is included in this variable
      target_season: "JAS" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
#        - name: District
#          key: 2
      season: "season1"
      predictor: "pnep"
      predictand: "bad-years"
      year: 2023
      issue_month: [3,4,5]
      freq: [15,30]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/djibouti"
      report: "https://google.com"

    madagascar:
      country: "madagascar"
      target_season: "DJF" #this is different from season which is used for the API
      mode:
        - name: National
          key: 0
        - name: Regional
          key: 1
      season: "season1"
      predictor: "pnep-v2"
      predictand: "bad-years-v3"
      year: 2024
      issue_month: [ 8,9,10 ]
      freq: [ 15, 25, 30 ]
      include_upcoming: false
      design_tool: "https://iridl.ldeo.columbia.edu/fbfmaproom2/madagascar"
      report: "https://google.com"